"""
Manually curated HP Fandom wiki categories -> NER label mapping.

These were selected after exploring the category tree and removing
subcategories that bleed into unrelated domains (e.g. "People in Locations").
Edit this dict to add/remove coverage, the crawl scripts read it directly.
"""

CATEGORIES: dict[str, list[str]] = {
    "CHAR": [
        "Wizards",
        "Dark wizards",
        "Death Eaters",
        "Death Eater defectors",
        "Unidentified Death Eaters",
        "Fictional Dark wizards",
        "Rookwood Gang",
        "Ashwinders (organisation)",
        "Poacher Pack",
        "Snatchers",
        "Unidentified Snatchers",
        "Unidentified Dark wizards",
        "Late-bloomers",
        "Ghosts",
        "Animal ghosts",
        "Ghost horses",
        "Unidentified ghosts",
        "Non-magic people",
        "Unidentified non-magic people",
        "Squibs",
    ],
    "LOC": [
        "Wizarding locations",
        "Apothecaries",
        "Broomstick shops",
        "Joke shops",
        "Wand shops",
        "British Ministry of Magic locations",
        "British Ministry of Magic courtrooms",
        "British Ministry of Magic research wing",
        "French Ministry of Magic locations",
        "German Ministry of Magic locations",
        "Erkstag",
        "Diagon Alley",
        "Carkitt Market",
        "Horizont Alley",
        "Knockturn Alley",
        "Leaky Cauldron",
        "Gringotts vaults",
        "Magical schools",
        "Beauxbatons",
        "Beauxbatons locations",
        "Castelobruxo",
        "Durmstrang",
        "Durmstrang locations",
        "Hogwarts",
        "Hogwarts locations",
        "Hogwarts Express",
        "Ilvermorny",
        "Ilvermorny locations",
        "Mahoutokoro",
        "Mahoutokoro locations",
        "Uagadou",
        "Magically protected locations",
        "Magical Congress of the United States of America locations",
        "Malfoy Manor",
        "Unplottable locations",
        "Azkaban",
        "Place Cachée",
        "Quidditch stadiums",
        "St Mungo's",
        "St Oswald's",
        "Wildlife reserves",
        "Magical Creatures Reserve",
        "Zonko's Joke Shop",
        "Wizarding towns",
        "Feldcroft",
        "Godric's Hollow",
        "Hogsmeade",
        "Shrieking Shack",
        "Three Broomsticks Inn",
        "Honeydukes",
        "Hogsmeade Post Office",
        "Ottery St Catchpole",
        "The Burrow",
    ],
    "ARTI": [
        "Magical objects",
        "Amulets",
        "Bludgers",
        "Golden Snitches",
        "Broomsticks",
        "Broomstick accessories",
        "Individual broomsticks",
        "Harry Potter's broomsticks",
        "Cauldrons",
        "Crystal balls",
        "Flying carpets",
        "Interdepartmental memos",
        "Portkeys",
        "Dark Magic artefacts",
        "Cursed objects",
        "Horcruxes",
        "Tom Riddle's Horcruxes",
        "Shrunken heads",
        "Goblin-made objects",
        "Ancient magic repositories",
        "Objects made by Ragnuk",
        "Potions",
        "Counter-serums",
        "Fire-based potions",
        "Mental potions",
        "Awakening potions",
        "Love potions",
        "Sleep potions",
        "Potion ingredients",
        "Unidentified potions",
        "Prank devices",
        "Weasleys' Wizard Wheezes",
        "Skiving Snackbox",
        "WonderWitch",
        "Explosive Enterprises",
        "Muggle Magic",
        "Protective objects",
        "Dark Detectors",
        "Fireproof objects",
        "Sentient objects",
        "Living books",
        "Portraits",
        "Paintings of creatures",
        "Unidentified portraits",
        "Suits of armour",
        "Armour pieces",
        "Gargoyles",
        "Wizard's Chess sets",
        "Wands",
        "Destroyed wands",
        "Wands by length",
        "Wands by material",
        "Wands by wandmaker",
        "Howlers",
        "Triwizard Tournament objects",
    ],
    "ORG": [
        "Organisations",
        "Advocacy groups",
        "Dumbledore's first army",
        "Goblin rebels",
        "Ranrok's Loyalists",
        "New Salem Philanthropic Society",
        "Nocturnal Order of Tricks and Magical Exhibitions",
        "Society for the Promotion of Elfish Welfare",
        "Businesses",
        "Banks",
        "Gringotts",
        "Broomstick manufacturers",
        "Cliques",
        "Dudley Dursley's gang",
        "Marauders",
        "Tom Riddle's gang",
        "Circle of Khanna",
        "Clubs",
        "Duelling Clubs",
        "Fan clubs",
        "Hogwarts clubs",
        "Hogwarts Gobstone Club",
        "Slug Club",
        "Inquisitorial Squad",
        "Keepers (ancient magic)",
        "Defence against the Dark Arts organisations",
        "Auror services",
        "Auror Office",
        "Gobstones organisations",
        "Gobstones teams",
        "Governments",
        "Magical governments",
        "International Confederation of Wizards",
        "Magical Congress of the United States of America",
        "Ministries of Magic",
        "Magical governments of the United Kingdom",
        "Law enforcement agencies",
        "Department of Magical Law Enforcement",
        "Muggle-Born Registration Commission",
        "Wizengamot",
        "Militias",
        "Terrorist groups",
        "Rookwood Gang",
        "Ashwinders (organisation)",
        "Poacher Pack",
        "Musical groups",
        "Frog Choir",
        "Place Cachée Jazz Band",
        "Weird Sisters",
        "Political parties",
        "R",
        "Magical schools",
        "Beauxbatons",
        "Castelobruxo",
        "Durmstrang",
        "Hogwarts",
        "Ilvermorny",
        "Mahoutokoro",
        "Uagadou",
        "Smeltings",
        "Sports teams",
        "Quidditch teams",
        "British and Irish Quidditch League Quidditch teams",
        "Hogwarts Quidditch teams",
        "National Quidditch teams",
    ],
    "CREA": [
        "Creatures",
        "Flobberworms", "Horklumps", "Augureys", "Bowtruckles",
        "Chizpurfles", "Clabberts", "Diricawls", "Fairies", "Ghouls",
        "Gnomes", "Grindylows", "Imps", "Jobberknolls", "Mooncalves",
        "Porlocks", "Puffskeins", "Ramoras", "Winged horses", "Abraxans",
        "Thestrals", "Ashwinders", "Billywigs", "Bundimuns", "Crups",
        "Doxies", "Dugbogs", "Fire Crabs", "Fwoopers", "Glumbumbles",
        "Hippocampi", "Hippogriffs", "Hodags", "Knarls", "Kneazles",
        "Leprechauns", "Lobalugs", "Mackled Malaclaws", "Mokes", "Murtlaps",
        "Nifflers", "Nogtails", "Pixies", "Plimpies", "Red Caps",
        "Salamanders", "Frost Salamanders", "Sea serpents", "Shrakes",
        "Streelers", "Centaurs", "Demiguises", "Erumpents", "Golden Snidgets",
        "Graphorns", "Griffins", "Kelpies", "Merpeople", "Selkies",
        "Occamies", "Phoenixes", "Re'ems", "Runespoors", "Snallygasters",
        "Sphinxes", "Thunderbirds", "Trolls", "Unicorns", "Yetis",
        "Acromantulas", "Basilisks", "Chimaeras", "Dragons", "Individual dragons",
        "Horned Serpents", "Manticores", "Nundus", "Quintapeds",
        "Wampus cats", "Werewolves",
        "Demons", "Water demons",
        "Beasts", "Beings", "Giants", "Half-giants", "Goblins",
        "Corrupted goblins", "Hags", "House-elves", "Vampires", "Veela",
        "Part-Veela",
        "Spirits", "Amortals", "Banshees", "Ghosts",
        "Shapeshifters", "Boggarts", "Maledictuses", "Metamorphmagi",
        "Obscurials",
        "Zombies", "Inferi", "Dwarfs", "Pukwudgies",
        "Chupacabras", "Classical Beasts", "Giant Squids", "Firedrakes",
        "Giant Dung Beetles", "Glow Bugs", "Jackalopes", "Leucrottas",
        "Matagots", "Qilins", "Swooping Evils", "Thornbacks",
        "Three-headed dogs", "Wyverns", "Zouwus", "Gargoyles",
        "Parasites", "Larvae",
    ],
    "SPELL": [
        "Spells",
        "Charms", "Dark charms", "Protective spells",
        "Curses", "Unforgivable Curses", "Hexes", "Jinxes", "Special Jinxes",
        "Counter-spells", "Counter-charms", "Counter-curses", "Counter-jinxes",
        "Untransfigurations",
        "Cleaning spells", "Healing spells", "Mental spells", "Opening spells",
        "Spell types", "Transfiguration spells", "Transforming spells",
        "Spells of known incantation", "Spells of unknown incantation",
        "Spells with a light", "Unidentified spells", "Unintentional spells",
    ],
}